#!/bin/sh

# Let's make ubuntu great again 

## Updating the system

sudo apt update
sudo apt upgrade -y

#
## remove snaps ew!

sudo snap remove $(snap list | awk '!/^Name|^core/ {print $1}')
sudo apt remove --purge -y snapd gnome-software-plugin-snap
sudo rm -rf /var/cache/snapd/
rm -fr ~/snap
cd /etc/apt/preferences.d/
sudo wget https://bit.ly/2XAEFEM --output-document=nosnap.pref

#
## installing esstinaia packages 

sudo apt install lightdm terminator git awesome blueman nemo firefox light xwallpaper mpv aria2 seahorse lxappearance zsh qt5ct qt5-style-plugins mpd mpdris2 ncmpcpp autojump fzf flameshot typecatcher gnome-disk-utility gcc python3-dev python3-pip python3-setuptools tor pandoc zsh-syntax-highlighting zsh-autosuggestions apt-file libx11-dev libxinerama-dev libxft-dev libxt-dev libxfixes-dev libxi-dev -y

### removing gnome shell
sudo apt remove gnome-shell -y

### cleaning up 
sudo apt autoclean -y && sudo apt autoremove -y

#
## installing 3rd party apps
mkdir $HOME/scriptcache
cd $HOME/scriptcache

## lf
wget https://github.com/gokcehan/lf/releases/download/r27/lf-linux-amd64.tar.gz
tar xzf lf-linux-amd64.tar.gz 
mv lf $HOME/.local/bin

### codium

#### add the key
wget -qO - https://gitlab.com/paulcarroty/vscodium-deb-rpm-repo/raw/master/pub.gpg \
    | gpg --dearmor \
    | sudo dd of=/usr/share/keyrings/vscodium-archive-keyring.gpg

#### adding the repo
echo 'deb [ signed-by=/usr/share/keyrings/vscodium-archive-keyring.gpg ] https://paulcarroty.gitlab.io/vscodium-deb-rpm-repo/debs vscodium main' \
    | sudo tee /etc/apt/sources.list.d/vscodium.list

### node
curl -fsSL https://deb.nodesource.com/setup_14.x | sudo -E bash -

### albert
echo 'deb http://download.opensuse.org/repositories/home:/manuelschneid3r/xUbuntu_20.04/ /' | sudo tee /etc/apt/sources.list.d/home:manuelschneid3r.list
curl -fsSL https://download.opensuse.org/repositories/home:manuelschneid3r/xUbuntu_20.04/Release.key | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/home_manuelschneid3r.gpg > /dev/null

### copyq
sudo add-apt-repository ppa:hluk/copyq -y

### qbittorrent
sudo add-apt-repository ppa:qbittorrent-team/qbittorrent-stable -y

### xdman
# Manual for now

### cryptomator
sudo add-apt-repository ppa:sebastian-stenzel/cryptomator -y

### breaktimer
wget https://github.com/tom-james-watson/breaktimer-app/releases/download/v0.9.0/BreakTimer.deb

sudo apt install ./BreakTimer.deb -y

### smplayer
sudo add-apt-repository ppa:rvm/smplayer -y 

### brave
sudo curl -fsSLo /usr/share/keyrings/brave-browser-archive-keyring.gpg https://brave-browser-apt-release.s3.brave.com/brave-browser-archive-keyring.gpg

echo "deb [signed-by=/usr/share/keyrings/brave-browser-archive-keyring.gpg arch=amd64] https://brave-browser-apt-release.s3.brave.com/ stable main"|sudo tee /etc/apt/sources.list.d/brave-browser-release.list

### starship
curl -sS https://starship.rs/install.sh | sh


### papirus icons
sudo add-apt-repository ppa:papirus/papirus -y

### neovim
sudo add-apt-repository ppa:neovim-ppa/stable -y

### gh
curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg
sudo chmod go+r /usr/share/keyrings/githubcli-archive-keyring.gpg
echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null


### installing all that and praying to god nothing bad happens 
sudo apt update
sudo apt install codium nodejs albert copyq qbittorrent papirus-icon-theme smplayer smtube smplayer-themes smplayer-skins brave-browser neovim gh  -y

#
## Build from source 

### xbanish
wget https://github.com/jcs/xbanish/archive/refs/tags/v1.8.tar.gz
tar xzf v1.8.tar.gz
cd xbanish-1.8
sudo make install
cd $HOME/scriptcache

### picom
wget https://github.com/yshui/picom/archive/refs/tags/v9.1.tar.gz
tar xzf v9.1.tar.gz
cd picom-9.1
sudo apt install libxext-dev libxcb1-dev libxcb-damage0-dev libxcb-xfixes0-dev libxcb-shape0-dev libxcb-render-util0-dev libxcb-render0-dev libxcb-randr0-dev libxcb-composite0-dev libxcb-image0-dev libxcb-present-dev libxcb-xinerama0-dev libxcb-glx0-dev libpixman-1-dev libdbus-1-dev libconfig-dev libgl1-mesa-dev libpcre2-dev libpcre3-dev libevdev-dev uthash-dev libev-dev libx11-xcb-dev meson -y
meson --buildtype=release . build
ninja -C build
sudo ninja -C build install 
cd $HOME/scriptcache

### yt-dlp
wget https://github.com/yt-dlp/yt-dlp/archive/refs/tags/2022.06.29.tar.gz
tar xzf 2022.06.29.tar.gz
cd yt-dlp-2022.06.29
sudo make install DESTDIR=/
cd $HOME/scriptcache

### Dmenu
git clone https://github.com/AhmedHalim96/dmenu
make
sudo make install
make clean
https://github.com/AhmedHalim96/dmenu
cd $HOME/scriptcache

### auto cpu frequency  
git clone https://github.com/AdnanHodzic/auto-cpufreq.git
cd auto-cpufreq && sudo ./auto-cpufreq-installer
sudo auto-cpufreq-install
cd $HOME/scriptcache

## installing some python packages pip install gallery-dl ueberzug thefuck

#
## Adding some settings 

### switching to zsh
sudo chsh $USER # and then enter /bin/zsh


### auto mount the hdd
#### do it through gnomedisks 
# mounting options nosuid,nodev,nofail,x-gvfs-show,users,permissions,exec 
# mounting point /mnt/Data
# identify as label=data


#
## Theming

### papirus icons
## do it through lxappearance & qt5ct 

### fonts noto sans and fira code
cd ~/.fonts
wget https://github.com/ryanoasis/nerd-fonts/releases/download/v2.1.0/FiraCode.zip
unzip FiraCode.zip
rm FiraCode.zip
cd $HOME/scriptcache

### sweet theme 
mkdir ~/.themes
cd ~/.themes
wget https://github.com/EliverLara/Sweet/releases/download/v3.0/Sweet-Dark.zip
unzip Sweet-Dark.zip
rm Sweet-Dark.zip
cd $HOME/scriptcache
# set it using lxappearance

#
## Cloning my dot config files
git clone  --bare  https://github.com/AhmedHalim96/dotfiles $HOME/.cfg 
alias dotfiles="/usr/bin/git --git-dir=$HOME/.cfg/ --work-tree=$HOME" 
dotfiles checkout -f master 
dotfiles submodule update --init --recursive -j 3 
dotfiles config --local status.showUntrackedFiles no

rm -rf ~/scriptcache
